### ISSUE TITLE
The extension shows an error for projects not using standard

### ISSUE THREAD

**Issue by justinmchase** [chenxsan/vscode-standardjs-old#3]
I know we're all using `standard` for all projects (right?) but _every once in a while_ I have to open one up that does not actually use standard. When that happens Code displays a toast error message saying that I need to install standard for it to work.

I think that that error message should not be shown and should instead shown the first time someone tries to format their code. 

Additionally if a different linter can be detected it should not be shown at all. What do you think? I will try to cook up a patch if this sounds acceptable.

**Comment by chenxsan** [comment]
@justinmchase 

Yes, it would be annoying to see that error message if one doesn't have `standard` installed globally.

> I think that that error message should not be shown and should instead shown the first time someone tries to format their code. 

I'm not sure of this. The linter should start to work when we open the file, not when we try to format the code.

> Additionally if a different linter can be detected it should not be shown at all.

vscode now has a lot of [linters](https://marketplace.visualstudio.com/vscode/Linters?sortBy=Downloads) for JavaScript, I'm not sure how we could detect them all.

How about inspecting the locally installed `standard`, if they aren't there, you might not want to use it in that project, so we don't show the error message at all.

**Comment by justinmchase** [comment]
I hadn't thought of installing it globally, I wouldn't want it to erroneously apply to projects that don't use it though so it still seems like it should have a way of detecting it in the project.

I do like your final suggestion, that sounds very good... but when would it show that message then?

Would it first look in `package.json` and see you have a dependency on standard, and then if standard can't actually be found then display the error?

**Comment by chenxsan** [comment]
👍, i agree with you. It should work.

On Wednesday, 15 June 2016, Justin Chase <notifications@github.com> wrote:

> I hadn't thought of installing it globally, I wouldn't want it to
> erroneously apply to projects that don't use it though so it still seems
> like it should have a way of detecting it in the project.
>
> I do like your final suggestion, that sounds very good... but when would
> it show that message then?
>
> Would it first look in package.json and see you have a dependency on
> standard, and then if standard can't actually be found then display the
> error?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/chenxsan/vscode-standardjs/issues/3#issuecomment-226231428>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABCnkIY2IDx3FyK6_arSmcE8pAwk0WEsks5qMB-AgaJpZM4I0kEp>
> .
>


-- 
Sam Chen

Blog - https://www.zfanw.com/blog/
